// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVkiSpqV4M_oIdZ6_64XY29rBjSuXDHLw',
    appId: '1:1074452706193:web:3b542d9122c389176d6030',
    messagingSenderId: '1074452706193',
    projectId: 'heavenly--havens',
    authDomain: 'heavenly--havens.firebaseapp.com',
    storageBucket: 'heavenly--havens.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxJu0LiW-2Ds_qvWqro8d1fMiLO5cmn_g',
    appId: '1:52161648870:android:fbac385b909d4ec21a8327',
    messagingSenderId: '52161648870',
    projectId: 'heavenlyhaven2-8940c',
    storageBucket: 'heavenlyhaven2-8940c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9G3XKW2A7M9kTQT_ZebS4-7ZRSnjdBrM',
    appId: '1:1074452706193:ios:5bd1c9b1ad3b5de06d6030',
    messagingSenderId: '1074452706193',
    projectId: 'heavenly--havens',
    storageBucket: 'heavenly--havens.firebasestorage.app',
    iosBundleId: 'com.example.heavenlyHavens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9G3XKW2A7M9kTQT_ZebS4-7ZRSnjdBrM',
    appId: '1:1074452706193:ios:5bd1c9b1ad3b5de06d6030',
    messagingSenderId: '1074452706193',
    projectId: 'heavenly--havens',
    storageBucket: 'heavenly--havens.firebasestorage.app',
    iosBundleId: 'com.example.heavenlyHavens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVkiSpqV4M_oIdZ6_64XY29rBjSuXDHLw',
    appId: '1:1074452706193:web:56d96ec636ade82d6d6030',
    messagingSenderId: '1074452706193',
    projectId: 'heavenly--havens',
    authDomain: 'heavenly--havens.firebaseapp.com',
    storageBucket: 'heavenly--havens.firebasestorage.app',
  );
}